# Generated by Django 4.2.4 on 2023-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsl_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicealert',
            name='entityId',
            field=models.CharField(max_length=50),
        ),
    ]
