# Generated by Django 4.2.4 on 2023-08-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsl_server', '0004_alter_servicealert_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicealert',
            old_name='descriptionText',
            new_name='descriptionText_en',
        ),
        migrations.RenameField(
            model_name='servicealert',
            old_name='headerText',
            new_name='headerText_en',
        ),
    ]
