# Generated by Django 4.2.4 on 2023-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsl_server', '0005_rename_descriptiontext_servicealert_descriptiontext_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicealert',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='servicealert',
            name='from_time',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicealert',
            name='to_time',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
