# Generated by Django 4.2.4 on 2023-08-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsl_server', '0006_remove_servicealert_timestamp_servicealert_from_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicealert',
            old_name='from_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='servicealert',
            old_name='to_time',
            new_name='start',
        ),
    ]
