# Generated by Django 4.2.4 on 2023-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsl_server', '0007_rename_from_time_servicealert_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicealert',
            name='end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
